# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  lane(:add_testers) do
    firebase_app_distribution_add_testers(
    project_number: "237759880526",
    emails: "foo@google.com,bar@google.com",
    group_alias: "qa-team" # (Optional) add testers to this group
    )
  end

  desc "Deploy a new version to Firebase App Distribution"
  lane :deploy_firebase_app_distribution do

      release = firebase_app_distribution(
          app: "1:237759880526:android:9c1c3ca0b1114fbb8d921f",
          apk_path: "../build/app/outputs/apk/release/app-release.apk",
          groups: "qa-team, trusted-testers"
      )
  end
end